use_frameworks!

platform :ios, '8.0'

target 'uniLib_ios_Example' do
  pod 'uniLib_ios', :path => '../'

  target 'uniLib_ios_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
